spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:e:/h2_db_file/querydsl
    username: sa
    password:
    driver-class-name : org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        use_sql_comments: true
logging:
  level:
    sql: debug


#jdbc:h2:e:/h2_db_file/querydsl
